services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FULL_NAME: ${NEXT_PUBLIC_FULL_NAME}
        NEXT_PUBLIC_EMAIL_ADDRESS: ${NEXT_PUBLIC_EMAIL_ADDRESS}
        NEXT_PUBLIC_PHONE_NUMBER: ${NEXT_PUBLIC_PHONE_NUMBER}
        NEXT_PUBLIC_STREET_ADDRESS: ${NEXT_PUBLIC_STREET_ADDRESS}
        NEXT_PUBLIC_CITY_ADDRESS: ${NEXT_PUBLIC_CITY_ADDRESS}
        NEXT_PUBLIC_GITHUB_USERNAME: ${NEXT_PUBLIC_GITHUB_USERNAME}
        NEXT_PUBLIC_LINKEDIN_USERNAME: ${NEXT_PUBLIC_LINKEDIN_USERNAME}
        NEXT_PUBLIC_INSTAGRAM_USERNAME: ${NEXT_PUBLIC_INSTAGRAM_USERNAME}
        NEXT_PUBLIC_ROOT_DOMAIN: ${NEXT_PUBLIC_ROOT_DOMAIN}
        NEXT_PUBLIC_SOFTWARE_DOMAIN: ${NEXT_PUBLIC_SOFTWARE_DOMAIN}
        NEXT_PUBLIC_PHOTOGRAPHY_DOMAIN: ${NEXT_PUBLIC_PHOTOGRAPHY_DOMAIN}
    image: my-portfolio-landing
    restart: unless-stopped
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/en"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_FULL_NAME=${NEXT_PUBLIC_FULL_NAME}
      - NEXT_PUBLIC_EMAIL_ADDRESS=${NEXT_PUBLIC_EMAIL_ADDRESS}
      - NEXT_PUBLIC_PHONE_NUMBER=${NEXT_PUBLIC_PHONE_NUMBER}
      - NEXT_PUBLIC_STREET_ADDRESS=${NEXT_PUBLIC_STREET_ADDRESS}
      - NEXT_PUBLIC_CITY_ADDRESS=${NEXT_PUBLIC_CITY_ADDRESS}
      - NEXT_PUBLIC_GITHUB_USERNAME=${NEXT_PUBLIC_GITHUB_USERNAME}
      - NEXT_PUBLIC_LINKEDIN_USERNAME=${NEXT_PUBLIC_LINKEDIN_USERNAME}
      - NEXT_PUBLIC_INSTAGRAM_USERNAME=${NEXT_PUBLIC_INSTAGRAM_USERNAME}
      - NEXT_PUBLIC_ROOT_DOMAIN=${NEXT_PUBLIC_ROOT_DOMAIN}
      - NEXT_PUBLIC_SOFTWARE_DOMAIN=${NEXT_PUBLIC_SOFTWARE_DOMAIN}
      - NEXT_PUBLIC_PHOTOGRAPHY_DOMAIN=${NEXT_PUBLIC_PHOTOGRAPHY_DOMAIN}
    networks:
      - coolify

networks:
  coolify:
    external: true
