services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FULL_NAME: ${NEXT_PUBLIC_FULL_NAME}
        NEXT_PUBLIC_EMAIL_ADDRESS: ${NEXT_PUBLIC_EMAIL_ADDRESS}
        NEXT_PUBLIC_PHONE_NUMBER: ${NEXT_PUBLIC_PHONE_NUMBER}
        NEXT_PUBLIC_STREET_ADDRESS: ${NEXT_PUBLIC_STREET_ADDRESS}
        NEXT_PUBLIC_CITY_ADDRESS: ${NEXT_PUBLIC_CITY_ADDRESS}
        NEXT_PUBLIC_GITHUB_USERNAME: ${NEXT_PUBLIC_GITHUB_USERNAME}
        NEXT_PUBLIC_LINKEDIN_USERNAME: ${NEXT_PUBLIC_LINKEDIN_USERNAME}
        NEXT_PUBLIC_INSTAGRAM_USERNAME: ${NEXT_PUBLIC_INSTAGRAM_USERNAME}
        NEXT_PUBLIC_ROOT_DOMAIN: ${NEXT_PUBLIC_ROOT_DOMAIN}
        NEXT_PUBLIC_SOFTWARE_DOMAIN: ${NEXT_PUBLIC_SOFTWARE_DOMAIN}
        NEXT_PUBLIC_PHOTOGRAPHY_DOMAIN: ${NEXT_PUBLIC_PHOTOGRAPHY_DOMAIN}
    container_name: portfolio-landing
    restart: always
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - NEXT_PUBLIC_FULL_NAME=${NEXT_PUBLIC_FULL_NAME}
      - NEXT_PUBLIC_EMAIL_ADDRESS=${NEXT_PUBLIC_EMAIL_ADDRESS}
      - NEXT_PUBLIC_PHONE_NUMBER=${NEXT_PUBLIC_PHONE_NUMBER}
      - NEXT_PUBLIC_STREET_ADDRESS=${NEXT_PUBLIC_STREET_ADDRESS}
      - NEXT_PUBLIC_CITY_ADDRESS=${NEXT_PUBLIC_CITY_ADDRESS}
      - NEXT_PUBLIC_GITHUB_USERNAME=${NEXT_PUBLIC_GITHUB_USERNAME}
      - NEXT_PUBLIC_LINKEDIN_USERNAME=${NEXT_PUBLIC_LINKEDIN_USERNAME}
      - NEXT_PUBLIC_INSTAGRAM_USERNAME=${NEXT_PUBLIC_INSTAGRAM_USERNAME}
      - NEXT_PUBLIC_ROOT_DOMAIN=${NEXT_PUBLIC_ROOT_DOMAIN}
      - NEXT_PUBLIC_SOFTWARE_DOMAIN=${NEXT_PUBLIC_SOFTWARE_DOMAIN}
      - NEXT_PUBLIC_PHOTOGRAPHY_DOMAIN=${NEXT_PUBLIC_PHOTOGRAPHY_DOMAIN}
